language: ruby
cache:
  bundler: true
  yarn: true
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- gem install bundler -v '2.0.1'
addons:
  postgresql: '9.6'
script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
